# Config file for automatic testing at travis-ci.org

language: python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip3 install -U tox-travis
install: pip3 install -r requirements.txt

# Command to run tests, e.g. python setup.py test
script: pytest

#notifications:
#  webhooks: https://coveralls.io/webhook?repo_token=lTgEF94FlDkvXVwvjcIRZiNsES446BFxe
#
